### ISSUE TITLE
Revive Flutter version for maintainability reasons?

### ISSUE THREAD

**Issue by MatsG23** [WangDaYeeeeee/GeometricWeather-iOS#6]
Since you started a Geometric Weather iOS version too, would it not make sense to revive the [Flutter version of the app](https://github.com/WangDaYeeeeee/GeometricWeather-Flutter)? This allows using one codebase for Android and iOS. I have good experiences in building Flutter apps and the performance of those. Apps like eBay, 4 Pics 1 Word, Yubico Authenticator and some Google apps are already using Flutter very successfully.
You may like or may not like my idea.

**Comment by HackZy01** [comment]
I think using Swift is the best choice for this app, Android already has Breezy Weather maintained better than this one
